"""Execute the production modern provider with controlled, Android-free test boundaries.

Not a framework/Binder/IKE/device test. The separate real API31 build and ABI
checks validate the stubbed boundary signatures against pinned framework samples.
"""
from pathlib import Path
import subprocess,sys,shutil
BASE=Path(__file__).resolve().parent
sys.path.insert(0,str(BASE.parent/'android11'))
from build_common import JAVA,TOOLS
OUT=BASE/'out/modern-iwlan-test'
if OUT.exists():shutil.rmtree(OUT)
SRC=OUT/'src';CLASSES=OUT/'classes'
STUBS={
'android/R.java':'''package android; public final class R {public static class drawable {public static int stat_sys_phone_call=1;}}''',
'android/app/Notification.java':'''package android.app; public class Notification {public static class Builder {public Builder(Object c,String s){} public Builder setSmallIcon(int n){return this;} public Builder setContentTitle(String s){return this;} public Builder setContentText(String s){return this;} public Builder setOngoing(boolean b){return this;} public Builder setOnlyAlertOnce(boolean b){return this;} public Notification build(){return new Notification();}}}''',
'android/app/NotificationChannel.java':'''package android.app; public class NotificationChannel {public NotificationChannel(String a,String b,int c){}}''',
'android/app/NotificationManager.java':'''package android.app; public class NotificationManager {public static int IMPORTANCE_LOW=1; public void createNotificationChannel(NotificationChannel c){}}''',
'android/os/Looper.java':'''package android.os; public class Looper {public static Looper getMainLooper(){return new Looper();}}''',
'android/os/Handler.java':'''package android.os; import java.util.*; public class Handler {private static final Queue<Runnable> q=new java.util.concurrent.ConcurrentLinkedQueue<>(); public Handler(Looper l){} public boolean post(Runnable r){q.add(r);return true;} public static void drain(){while(!q.isEmpty())q.remove().run();}}''',
'android/net/LinkAddress.java':'''package android.net; import java.net.*; public class LinkAddress {private final InetAddress a;private final int p;public LinkAddress(InetAddress a,int p){this.a=a;this.p=p;}public InetAddress getAddress(){return a;}public int getPrefixLength(){return p;}}''',
'android/net/LinkProperties.java':'''package android.net; import java.util.*; public class LinkProperties {private final List<LinkAddress> a=new ArrayList<>(); public LinkProperties(){}public LinkProperties(LinkProperties source){a.addAll(source.a);}public List<LinkAddress> getLinkAddresses(){return Collections.unmodifiableList(a);}public void addLinkAddress(LinkAddress x){a.add(x);}public void clear(){a.clear();}}''',
'android/telephony/AccessNetworkConstants.java':'''package android.telephony; public class AccessNetworkConstants {public static class AccessNetworkType {public static final int IWLAN=5;}}''',
'android/telephony/DataFailCause.java':'''package android.telephony; public class DataFailCause {public static final int NONE=0,ERROR_UNSPECIFIED=65535,MATCH_ALL_RULE_NOT_ALLOWED=2254,SLICE_REJECTED=2253,SERVICE_OPTION_NOT_SUPPORTED=32,DATA_ROAMING_SETTINGS_DISABLED=2064;}''',
'android/telephony/SubscriptionInfo.java':'''package android.telephony;public class SubscriptionInfo {private final int sub;public SubscriptionInfo(int sub){this.sub=sub;}public int getSubscriptionId(){return sub;}}''',
'android/util/Log.java':'''package android.util;public class Log {public static int i(String a,String b){return 0;}}''',
'android/telephony/data/ApnSetting.java':'''package android.telephony.data; public class ApnSetting {public static final int PROTOCOL_IP=0,PROTOCOL_IPV6=1,PROTOCOL_IPV4V6=2;}''',
'android/telephony/data/DataProfile.java':'''package android.telephony.data;public class DataProfile {private final String apn;private final int normal,roam;public DataProfile(String apn,int normal,int roam){this.apn=apn;this.normal=normal;this.roam=roam;}public String getApn(){return apn;}public int getProtocolType(){return normal;}public int getRoamingProtocolType(){return roam;}}''',
'android/telephony/data/NetworkSliceInfo.java':'''package android.telephony.data;public class NetworkSliceInfo {}''',
'android/telephony/data/TrafficDescriptor.java':'''package android.telephony.data;public class TrafficDescriptor {}''',
'android/telephony/data/DataServiceCallback.java':'''package android.telephony.data;import java.util.*;public class DataServiceCallback {public static final int RESULT_SUCCESS=0,RESULT_ERROR_UNSUPPORTED=1,RESULT_ERROR_INVALID_ARG=2,RESULT_ERROR_BUSY=3,RESULT_ERROR_ILLEGAL_STATE=4;public int count,result=-1;public DataCallResponse response;public List<DataCallResponse> list;public void onSetupDataCallComplete(int r,DataCallResponse d){count++;result=r;response=d;}public void onDeactivateDataCallComplete(int r){count++;result=r;}public void onHandoverStarted(int r){count++;result=r;}public void onHandoverCancelled(int r){count++;result=r;}public void onRequestDataCallListComplete(int r,List<DataCallResponse> d){count++;result=r;list=d;}public void onSetInitialAttachApnComplete(int r){}public void onSetDataProfileComplete(int r){}}''',
'android/telephony/data/DataService.java':'''package android.telephony.data;import android.net.*;import java.util.*;public class DataService {public static final int REQUEST_REASON_NORMAL=1,REQUEST_REASON_SHUTDOWN=2,REQUEST_REASON_HANDOVER=3;public void onCreate(){}public <T>T getSystemService(Class<T> c){try{return c.getDeclaredConstructor().newInstance();}catch(Exception e){throw new RuntimeException(e);}}public void startForeground(int id,Object n){}public DataServiceProvider onCreateDataServiceProvider(int slot){return null;}public abstract class DataServiceProvider {private final int slot;public int notifications;public List<DataCallResponse> lastList;public DataServiceProvider(int slot){this.slot=slot;}public int getSlotIndex(){return slot;}public void setupDataCall(int rat,DataProfile profile,boolean roaming,boolean allow,int reason,LinkProperties source,DataServiceCallback cb){}public void setupDataCall(int rat,DataProfile profile,boolean roaming,boolean allow,int reason,LinkProperties source,int pdu,NetworkSliceInfo slice,TrafficDescriptor traffic,boolean all,DataServiceCallback cb){}public void notifyDataCallListChanged(List<DataCallResponse> list){notifications++;lastList=list;}public void deactivateDataCall(int id,int reason,DataServiceCallback cb){}public void requestDataCallList(DataServiceCallback cb){}public void startHandover(int id,DataServiceCallback cb){}public void cancelHandover(int id,DataServiceCallback cb){}public void setInitialAttachApn(DataProfile p,boolean r,DataServiceCallback cb){}public void setDataProfile(List<DataProfile> p,boolean r,DataServiceCallback cb){}public abstract void close();}}''',
'android/telephony/data/DataCallResponse.java':'''package android.telephony.data;import java.util.*;import java.net.*;import android.net.*;public class DataCallResponse {public static final int LINK_STATUS_ACTIVE=2,HANDOVER_FAILURE_MODE_DO_FALLBACK=1,HANDOVER_FAILURE_MODE_LEGACY=0;public int id,cause,status,protocol,mtu4,mtu6,pdu,mode,retry;public String iface;public List<LinkAddress> addresses;public List<InetAddress> gateways;public List<LinkAddress> getAddresses(){return addresses;}public static class Builder {private final DataCallResponse d=new DataCallResponse();public Builder setId(int n){d.id=n;return this;}public Builder setCause(int n){d.cause=n;return this;}public Builder setSuggestedRetryTime(int n){d.retry=n;return this;}public Builder setHandoverFailureMode(int n){d.mode=n;return this;}public Builder setLinkStatus(int n){d.status=n;return this;}public Builder setProtocolType(int n){d.protocol=n;return this;}public Builder setInterfaceName(String s){d.iface=s;return this;}public Builder setAddresses(List<LinkAddress> a){d.addresses=new ArrayList<>(a);return this;}public Builder setDnsAddresses(List<InetAddress> a){return this;}public Builder setPcscfAddresses(List<InetAddress> a){return this;}public Builder setGatewayAddresses(List<InetAddress> a){d.gateways=new ArrayList<>(a);return this;}public Builder setMtu(int n){return this;}public Builder setMtuV4(int n){d.mtu4=n;return this;}public Builder setMtuV6(int n){d.mtu6=n;return this;}public Builder setPduSessionId(int n){d.pdu=n;return this;}public DataCallResponse build(){return d;}}}''',
'dev/codex/vowifi/common/StackProfile.java':'''package dev.codex.vowifi.common;import android.telephony.*;public class StackProfile {public static int[] subs={11,22};public static SubscriptionInfo selectedSubscription(Object c,int slot){return subs[slot]<0?null:new SubscriptionInfo(subs[slot]);}}''',
'dev/codex/vowifi/iwlan/EpdgSession.java':'''package dev.codex.vowifi.iwlan;import java.util.*;import java.net.*;import android.net.*;public class EpdgSession {public interface Listener {void opened(String iface,List<LinkAddress> a,List<InetAddress> d,List<InetAddress> p);void closed(String reason);}public static final List<EpdgSession> created=new ArrayList<>();public final int slot,sub;public final EpdgAddressRequest request;public final Listener listener;public int closes;public EpdgSession(Object c,int slot,int sub,EpdgAddressRequest request,Listener listener){this.slot=slot;this.sub=sub;this.request=request;this.listener=listener;created.add(this);}public void start(){}public void close(){closes++;}public void open(List<LinkAddress> addresses)throws Exception {listener.opened("fixture-ipsec",addresses,Collections.emptyList(),Collections.singletonList(InetAddress.getByName("192.0.2.1")));}}''',
}
for name,source in STUBS.items():
    p=SRC/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(source,encoding='utf-8')
sources=sorted(SRC.rglob('*.java'))+[
    BASE.parent/'android11/stack/iwlan/EpdgAddressRequest.java',
    BASE.parent/'android12/iwlan/ModernIwlanDataService.java',
    BASE/'tests/ModernIwlanContractTest.java']
subprocess.run([JAVA,'-jar',str(TOOLS/'ecj.jar'),'-encoding','UTF-8','-source','8','-target','8','-proc:none',
    '-d',str(CLASSES),*map(str,sources)],check=True)
subprocess.run([JAVA,'-cp',str(CLASSES),'dev.codex.vowifi.iwlan.ModernIwlanContractTest'],check=True)
