// SPDX-License-Identifier: GPL-2.0
import android.os.*;
import java.io.*;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import org.json.*;

/** Read-only guard for two original API33 installation-stage records. */
public final class Api33RecordedRecoveryAudit {
    static String checkpoint="profile",observedOwnerSchema="unobserved",observedOwnerPhase="unobserved";
    static final File ROOT=new File("/data/local/tmp/codex-modern-installation-tests");
    static final File CARRIER=new File("/data/local/tmp/codex-modern-persistence-tests");
    static final Set<String> BASELINES=new HashSet<>(Arrays.asList("ad06b3495d2f3ba757f6b3760b15d15250ac5af7e3d23ebf73bd5e6c2e02d34d","023b14921f1ee1ba69ff30285376e27b89bb9e5958f951c4d2a8fc307cf0aa5f"));
    static final Set<String> OUTERS=new HashSet<>(Arrays.asList("3e96ebaf8d082fea3ad8ae1fdb4930ecc36bd37e1aa53f7c130fd32dbac1f79e","9433c8bf616f5dce995b36a3e1c55d42b8fd1d6e8bea3e70f42f81bfc06126aa"));
    static void canonical(File path)throws Exception{if(!path.getAbsoluteFile().equals(path.getCanonicalFile())||Files.isSymbolicLink(path.toPath()))throw new IOException("fixture-alias-refused");}
    static Properties read(File path)throws Exception{canonical(path);if(!path.isFile()||path.length()>32768)throw new IOException("fixture-record-refused");Properties value=new Properties();try(InputStream stream=new FileInputStream(path)){value.load(stream);}return value;}
    static String digest(File path)throws Exception{canonical(path);if(!path.isFile()||path.length()>67108864)throw new IOException("fixture-digest-refused");MessageDigest sha=MessageDigest.getInstance("SHA-256");try(InputStream stream=new FileInputStream(path)){byte[] bytes=new byte[8192];int count;while((count=stream.read(bytes))!=-1)sha.update(bytes,0,count);}return hex(sha.digest());}
    static String hex(byte[] bytes){StringBuilder value=new StringBuilder();for(byte b:bytes)value.append(String.format(Locale.ROOT,"%02x",b&255));return value.toString();}
    static void profile()throws Exception{if(android.os.Process.myUid()!=0||Build.VERSION.SDK_INT!=33||!"1".equals(SystemProperties.get("ro.kernel.qemu"))||!"CodexVoWiFiApi33".equals(SystemProperties.get("ro.boot.qemu.avd_name")))throw new SecurityException("owned-api33-required");}
    private int files,owners,legacyOwners,installations,pending,carriers,pendingCarriers;private final ArrayList<String> ownerDigests=new ArrayList<>(),outerDigests=new ArrayList<>();
    private boolean archived(File path,Properties value)throws Exception{File parent=path.getParentFile();if(!Arrays.asList("2","3").contains(value.getProperty("schema"))||!"ARCHIVING".equals(value.getProperty("phase"))||!"history".equals(parent.getParentFile().getName())||!parent.getName().matches("slot-[0-7]-sub-[0-9]+-[0-9a-f]{32}"))return false;File phase=new File(parent,"carrier/phase");canonical(phase);return phase.isFile()&&phase.length()<65&&"RESTORED".equals(new String(Files.readAllBytes(phase.toPath()),"UTF-8"));}
    private void scan(File path,int depth)throws Exception{
        canonical(path);if(depth>12||!path.isDirectory())throw new IOException("fixture-tree-refused");File[] entries=path.listFiles();if(entries==null||entries.length>512)throw new IOException("fixture-inventory-refused");Arrays.sort(entries,Comparator.comparing(File::getName));
        for(File file:entries){if(++files>10000)throw new IOException("fixture-bound-refused");canonical(file);if(file.isDirectory()){scan(file,depth+1);continue;}
            if("selection.properties".equals(file.getName())){checkpoint="owner-record";Properties record=read(file);String schema=record.getProperty("schema");observedOwnerSchema=Arrays.asList("1","2","3").contains(schema)?schema:"unknown";observedOwnerPhase=Arrays.asList("RESTORED","ARCHIVING","ACTIVE","RESTORING","PREPARING","PREPARED").contains(record.getProperty("phase"))?record.getProperty("phase"):"unknown";if(!Arrays.asList("1","2","3").contains(schema)||!(Build.VERSION.SDK_INT+":"+Build.FINGERPRINT).equals(record.getProperty("build"))||!("RESTORED".equals(record.getProperty("phase"))||archived(file,record))||!"false".equals(record.getProperty("mode_owned"))||Boolean.parseBoolean(record.getProperty("recovery.pending_owner")))throw new IOException("unfinished-owner-refused");owners++;if(!"3".equals(schema))legacyOwners++;ownerDigests.add(ROOT.toPath().relativize(file.toPath()).toString()+":"+digest(file));}
            else if("baseline.properties".equals(file.getName())){Properties record=read(file);if(!"1".equals(record.getProperty("schema"))||!(Build.VERSION.SDK_INT+":"+Build.FINGERPRINT).equals(record.getProperty("build")))throw new IOException("installation-record-refused");if(!"RESTORED".equals(record.getProperty("phase"))){if(!"PREPARED".equals(record.getProperty("phase"))||!BASELINES.contains(digest(file)))throw new IOException("unknown-pending-installation-refused");pending++;}installations++;}
            else if("outer.properties".equals(file.getName()))outerDigests.add(ROOT.toPath().relativize(file.toPath()).toString()+":"+digest(file));
        }
    }
    private static String aggregate(ArrayList<String> values)throws Exception{Collections.sort(values);MessageDigest sha=MessageDigest.getInstance("SHA-256");for(String value:values)sha.update((value+"\n").getBytes("UTF-8"));return hex(sha.digest());}
    static JSONObject inspect()throws Exception{return inspect(false);}
    static JSONObject inspect(boolean allowOriginalRestoredFile)throws Exception{
        profile();checkpoint="record-tree";Api33RecordedRecoveryAudit audit=new Api33RecordedRecoveryAudit();audit.scan(ROOT,0);checkpoint="carrier-inventory";canonical(CARRIER);File[] cores=CARRIER.listFiles();if(cores==null||cores.length>512)throw new IOException("carrier-inventory-refused");
        for(File core:cores)if(core.getName().startsWith("slot-")){canonical(core);if(!core.isDirectory())throw new IOException("carrier-state-refused");File phase=new File(core,"phase");canonical(phase);File[] contents=core.listFiles();if(!phase.exists()&&contents!=null&&contents.length==0)continue;if(!phase.isFile()||phase.length()>64)throw new IOException("unfinished-carrier-refused");String stage=new String(Files.readAllBytes(phase.toPath()),"UTF-8");if(!"RESTORED".equals(stage)){if(!allowOriginalRestoredFile||!"RESTORED_FILE".equals(stage)||!"9fb1923dfc09aa175b7d76fabed135bebf36e5cb7b4a8c3ee03398316c0cb634".equals(digest(phase)))throw new IOException("unfinished-carrier-refused");audit.pendingCarriers++;}audit.carriers++;}
        for(String path:new String[]{"/data/adb/codex_vowifi_stack_modern/installation/baseline.properties","/data/adb/codex_vowifi_stack_modern/coordination/owners"})if(new File(path).exists())throw new IOException("production-state-refused");
        return new JSONObject().put("schema",1).put("sdk",33).put("read_only",true).put("status","observed").put("pending_installation_count",audit.pending).put("installation_records",audit.installations).put("owner_records",audit.owners).put("legacy_restored_owner_records",audit.legacyOwners).put("all_fixture_carrier_phases_restored",audit.pendingCarriers==0).put("pending_carrier_count",audit.pendingCarriers).put("carrier_records",audit.carriers).put("all_owner_records_finished",true).put("production_owner_state_absent",true).put("owner_records_aggregate_sha256",aggregate(audit.ownerDigests)).put("outer_records_aggregate_sha256",aggregate(audit.outerDigests));
    }
    public static void main(String[] args){JSONObject result=new JSONObject();boolean success=false;try{if(args.length!=0)throw new IllegalArgumentException("no-arguments-required");result=inspect();success=true;}catch(Throwable error){try{Set<String> safe=new HashSet<>(Arrays.asList("owned-api33-required","fixture-alias-refused","fixture-record-refused","fixture-digest-refused","fixture-tree-refused","fixture-inventory-refused","fixture-bound-refused","unfinished-owner-refused","installation-record-refused","unknown-pending-installation-refused","carrier-inventory-refused","carrier-state-refused","unfinished-carrier-refused","production-state-refused","no-arguments-required"));result.put("status","refused").put("error",error.getClass().getSimpleName()).put("reason",safe.contains(error.getMessage())?error.getMessage():"unclassified").put("checkpoint",checkpoint).put("observed_owner_schema",observedOwnerSchema).put("observed_owner_phase",observedOwnerPhase);}catch(Exception ignored){}}System.out.println(result);System.exit(success?0:1);}
}
